### ISSUE TITLE
round schedule is showing every drivers information

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/direct-delivery#187] opened 2015-04-24 16:57 UTC
when the round is clicked from the schedule tab, every driver's schedule is presented. it should only be logged in driver's schedule

**Comment by jofomah** [comment] 2015-04-24 21:09
This is actually not a bug on the software, seems to be due to this https://github.com/pouchdb/pouchdb/issues/3543 and https://github.com/pouchdb/pouchdb/issues/3606

This means that PouchDB v3.3.0 has a bug that ignores filter replication settings and replication everything, was fixed in v3.4.0 and was also working in v3.2.1 which was the version used at the time of implementing sync feature.

i suggest
1. we either downgrade to v3.2.1 (though it does not have persistent sync retry) or 
2. just filter daily delivery at schedule page by driver id (a quick hack) if we really want to fix this without breaking things.
3. upgrade to v3.4.0 already did  but the program started acting up.

i think option no 2 is the best alternative if we want this fixed in this release cycle.

**Comment by janetbutts** [comment] 2015-04-25 09:38
I like #2 if we can test it in time. I don't want to make any major changes at this point.

**Closed** 2015-04-28 09:30 UTC
